// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file platform/locator/v1/locator.proto (package platform.locator.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LocateRequest, LocateResponse, LocatorMessage, RegisterRequest, RegisterResponse, ServerMessage } from "./locator_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.locator.v1.Locator
 */
export const Locator = {
  typeName: "platform.locator.v1.Locator",
  methods: {
    /**
     * Register registers the Home Cloud server to begin synchronization with the locator server
     *
     * @generated from rpc platform.locator.v1.Locator.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Locate asks the Locator server to return the location of the Home Cloud server referenced by the provided server_id
     *
     * @generated from rpc platform.locator.v1.Locator.Locate
     */
    locate: {
      name: "Locate",
      I: LocateRequest,
      O: LocateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Connect establishes a stream between a Home Cloud server which negotiates location information for clients calling Locate
     *
     * @generated from rpc platform.locator.v1.Locator.Connect
     */
    connect: {
      name: "Connect",
      I: ServerMessage,
      O: LocatorMessage,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

