service:
  name: home-cloud-daemon
  domain: platform
  network:
    port: 9000
    bind_address: localhost

daemon:
  server: http://localhost:8000
  address: 192.168.1.174
  domain: local
  hostnames:
    - home-cloud
    - hello
    - photos
