// @generated by protoc-gen-es v1.10.0 with parameter "target=js"
// @generated from file platform/daemon/v1/daemon.proto (package platform.daemon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { SystemStats } from "./system_pb.js";

/**
 * @generated from message platform.daemon.v1.ShutdownHostRequest
 */
export const ShutdownHostRequest = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.ShutdownHostRequest",
  [],
);

/**
 * @generated from message platform.daemon.v1.ShutdownHostResponse
 */
export const ShutdownHostResponse = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.ShutdownHostResponse",
  [],
);

/**
 * @generated from message platform.daemon.v1.RebootHostRequest
 */
export const RebootHostRequest = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.RebootHostRequest",
  [],
);

/**
 * @generated from message platform.daemon.v1.RebootHostResponse
 */
export const RebootHostResponse = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.RebootHostResponse",
  [],
);

/**
 * @generated from message platform.daemon.v1.SystemStatsRequest
 */
export const SystemStatsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.SystemStatsRequest",
  [],
);

/**
 * @generated from message platform.daemon.v1.SystemStatsResponse
 */
export const SystemStatsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.SystemStatsResponse",
  () => [
    { no: 1, name: "stats", kind: "message", T: SystemStats },
  ],
);

/**
 * @generated from message platform.daemon.v1.VersionRequest
 */
export const VersionRequest = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.VersionRequest",
  [],
);

/**
 * @generated from message platform.daemon.v1.VersionResponse
 */
export const VersionResponse = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.VersionResponse",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.daemon.v1.UpgradeRequest
 */
export const UpgradeRequest = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.UpgradeRequest",
  () => [
    { no: 1, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.daemon.v1.UpgradeResponse
 */
export const UpgradeResponse = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.UpgradeResponse",
  [],
);

/**
 * @generated from message platform.daemon.v1.UpgradeKubernetesRequest
 */
export const UpgradeKubernetesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.UpgradeKubernetesRequest",
  () => [
    { no: 1, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.daemon.v1.UpgradeKubernetesResponse
 */
export const UpgradeKubernetesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.UpgradeKubernetesResponse",
  [],
);

/**
 * @generated from message platform.daemon.v1.CreateVolumeRequest
 */
export const CreateVolumeRequest = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.CreateVolumeRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "min_size", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "max_size", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.daemon.v1.CreateVolumeResponse
 */
export const CreateVolumeResponse = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.CreateVolumeResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.daemon.v1.DeleteVolumeRequest
 */
export const DeleteVolumeRequest = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.DeleteVolumeRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.daemon.v1.DeleteVolumeResponse
 */
export const DeleteVolumeResponse = /*@__PURE__*/ proto3.makeMessageType(
  "platform.daemon.v1.DeleteVolumeResponse",
  [],
);

