// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts"
// @generated from file platform/daemon/v1/daemon.proto (package platform.daemon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { RebootHostRequest, RebootHostResponse, ShutdownHostRequest, ShutdownHostResponse, SystemStatsRequest, SystemStatsResponse } from "./daemon_pb.js";

/**
 * @generated from rpc platform.daemon.v1.DaemonService.ShutdownHost
 */
export const shutdownHost = {
  localName: "shutdownHost",
  name: "ShutdownHost",
  kind: MethodKind.Unary,
  I: ShutdownHostRequest,
  O: ShutdownHostResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.RebootHost
 */
export const rebootHost = {
  localName: "rebootHost",
  name: "RebootHost",
  kind: MethodKind.Unary,
  I: RebootHostRequest,
  O: RebootHostResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.SystemStats
 */
export const systemStats = {
  localName: "systemStats",
  name: "SystemStats",
  kind: MethodKind.Unary,
  I: SystemStatsRequest,
  O: SystemStatsResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;
