// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: platform/daemon/v1/daemon.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShutdownHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutdownHostRequest) Reset() {
	*x = ShutdownHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownHostRequest) ProtoMessage() {}

func (x *ShutdownHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownHostRequest.ProtoReflect.Descriptor instead.
func (*ShutdownHostRequest) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type ShutdownHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutdownHostResponse) Reset() {
	*x = ShutdownHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownHostResponse) ProtoMessage() {}

func (x *ShutdownHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownHostResponse.ProtoReflect.Descriptor instead.
func (*ShutdownHostResponse) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_daemon_proto_rawDescGZIP(), []int{1}
}

type RebootHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RebootHostRequest) Reset() {
	*x = RebootHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebootHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootHostRequest) ProtoMessage() {}

func (x *RebootHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootHostRequest.ProtoReflect.Descriptor instead.
func (*RebootHostRequest) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_daemon_proto_rawDescGZIP(), []int{2}
}

type RebootHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RebootHostResponse) Reset() {
	*x = RebootHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebootHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootHostResponse) ProtoMessage() {}

func (x *RebootHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootHostResponse.ProtoReflect.Descriptor instead.
func (*RebootHostResponse) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_daemon_proto_rawDescGZIP(), []int{3}
}

var File_platform_daemon_v1_daemon_proto protoreflect.FileDescriptor

var file_platform_daemon_v1_daemon_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x15, 0x0a, 0x13, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13,
	0x0a, 0x11, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd3, 0x01, 0x0a, 0x0d, 0x44, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x63, 0x0a, 0x0c, 0x53,
	0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x27, 0x2e, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5d, 0x0a, 0x0a, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x25,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x62, 0x6f, 0x6f,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f,
	0x6d, 0x65, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_daemon_v1_daemon_proto_rawDescOnce sync.Once
	file_platform_daemon_v1_daemon_proto_rawDescData = file_platform_daemon_v1_daemon_proto_rawDesc
)

func file_platform_daemon_v1_daemon_proto_rawDescGZIP() []byte {
	file_platform_daemon_v1_daemon_proto_rawDescOnce.Do(func() {
		file_platform_daemon_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_daemon_v1_daemon_proto_rawDescData)
	})
	return file_platform_daemon_v1_daemon_proto_rawDescData
}

var file_platform_daemon_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platform_daemon_v1_daemon_proto_goTypes = []any{
	(*ShutdownHostRequest)(nil),  // 0: platform.daemon.v1.ShutdownHostRequest
	(*ShutdownHostResponse)(nil), // 1: platform.daemon.v1.ShutdownHostResponse
	(*RebootHostRequest)(nil),    // 2: platform.daemon.v1.RebootHostRequest
	(*RebootHostResponse)(nil),   // 3: platform.daemon.v1.RebootHostResponse
}
var file_platform_daemon_v1_daemon_proto_depIdxs = []int32{
	0, // 0: platform.daemon.v1.DaemonService.ShutdownHost:input_type -> platform.daemon.v1.ShutdownHostRequest
	2, // 1: platform.daemon.v1.DaemonService.RebootHost:input_type -> platform.daemon.v1.RebootHostRequest
	1, // 2: platform.daemon.v1.DaemonService.ShutdownHost:output_type -> platform.daemon.v1.ShutdownHostResponse
	3, // 3: platform.daemon.v1.DaemonService.RebootHost:output_type -> platform.daemon.v1.RebootHostResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platform_daemon_v1_daemon_proto_init() }
func file_platform_daemon_v1_daemon_proto_init() {
	if File_platform_daemon_v1_daemon_proto != nil {
		return
	}
	file_platform_daemon_v1_system_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_platform_daemon_v1_daemon_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ShutdownHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_daemon_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ShutdownHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_daemon_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RebootHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_daemon_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RebootHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_daemon_v1_daemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_daemon_v1_daemon_proto_goTypes,
		DependencyIndexes: file_platform_daemon_v1_daemon_proto_depIdxs,
		MessageInfos:      file_platform_daemon_v1_daemon_proto_msgTypes,
	}.Build()
	File_platform_daemon_v1_daemon_proto = out.File
	file_platform_daemon_v1_daemon_proto_rawDesc = nil
	file_platform_daemon_v1_daemon_proto_goTypes = nil
	file_platform_daemon_v1_daemon_proto_depIdxs = nil
}
