// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file platform/daemon/v1/daemon.proto (package platform.daemon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RebootHostRequest, RebootHostResponse, ShutdownHostRequest, ShutdownHostResponse, SystemStatsRequest, SystemStatsResponse } from "./daemon_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.daemon.v1.DaemonService
 */
export const DaemonService = {
  typeName: "platform.daemon.v1.DaemonService",
  methods: {
    /**
     * @generated from rpc platform.daemon.v1.DaemonService.ShutdownHost
     */
    shutdownHost: {
      name: "ShutdownHost",
      I: ShutdownHostRequest,
      O: ShutdownHostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.daemon.v1.DaemonService.RebootHost
     */
    rebootHost: {
      name: "RebootHost",
      I: RebootHostRequest,
      O: RebootHostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.daemon.v1.DaemonService.SystemStats
     */
    systemStats: {
      name: "SystemStats",
      I: SystemStatsRequest,
      O: SystemStatsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

