// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts"
// @generated from file platform/daemon/v1/daemon.proto (package platform.daemon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { AddLocatorServerRequest, AddLocatorServerResponse, AddWireguardInterfaceRequest, AddWireguardInterfaceResponse, AddWireguardPeerRequest, AddWireguardPeerResponse, InitializeHostRequest, InitializeHostResponse, RebootHostRequest, RebootHostResponse, RemoveLocatorServerRequest, RemoveLocatorServerResponse, RemoveWireguardInterfaceRequest, RemoveWireguardInterfaceResponse, RemoveWireguardPeerRequest, RemoveWireguardPeerResponse, SetSTUNServerRequest, SetSTUNServerResponse, ShutdownHostRequest, ShutdownHostResponse } from "./daemon_pb.js";

/**
 * @generated from rpc platform.daemon.v1.DaemonService.ShutdownHost
 */
export const shutdownHost = {
  localName: "shutdownHost",
  name: "ShutdownHost",
  kind: MethodKind.Unary,
  I: ShutdownHostRequest,
  O: ShutdownHostResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.RebootHost
 */
export const rebootHost = {
  localName: "rebootHost",
  name: "RebootHost",
  kind: MethodKind.Unary,
  I: RebootHostRequest,
  O: RebootHostResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.InitializeHost
 */
export const initializeHost = {
  localName: "initializeHost",
  name: "InitializeHost",
  kind: MethodKind.Unary,
  I: InitializeHostRequest,
  O: InitializeHostResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.AddWireguardInterface
 */
export const addWireguardInterface = {
  localName: "addWireguardInterface",
  name: "AddWireguardInterface",
  kind: MethodKind.Unary,
  I: AddWireguardInterfaceRequest,
  O: AddWireguardInterfaceResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.RemoveWireguardInterface
 */
export const removeWireguardInterface = {
  localName: "removeWireguardInterface",
  name: "RemoveWireguardInterface",
  kind: MethodKind.Unary,
  I: RemoveWireguardInterfaceRequest,
  O: RemoveWireguardInterfaceResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.AddWireguardPeer
 */
export const addWireguardPeer = {
  localName: "addWireguardPeer",
  name: "AddWireguardPeer",
  kind: MethodKind.Unary,
  I: AddWireguardPeerRequest,
  O: AddWireguardPeerResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.RemoveWireguardPeer
 */
export const removeWireguardPeer = {
  localName: "removeWireguardPeer",
  name: "RemoveWireguardPeer",
  kind: MethodKind.Unary,
  I: RemoveWireguardPeerRequest,
  O: RemoveWireguardPeerResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.SetSTUNServer
 */
export const setSTUNServer = {
  localName: "setSTUNServer",
  name: "SetSTUNServer",
  kind: MethodKind.Unary,
  I: SetSTUNServerRequest,
  O: SetSTUNServerResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.AddLocatorServer
 */
export const addLocatorServer = {
  localName: "addLocatorServer",
  name: "AddLocatorServer",
  kind: MethodKind.Unary,
  I: AddLocatorServerRequest,
  O: AddLocatorServerResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;

/**
 * @generated from rpc platform.daemon.v1.DaemonService.RemoveLocatorServer
 */
export const removeLocatorServer = {
  localName: "removeLocatorServer",
  name: "RemoveLocatorServer",
  kind: MethodKind.Unary,
  I: RemoveLocatorServerRequest,
  O: RemoveLocatorServerResponse,
  service: {
    typeName: "platform.daemon.v1.DaemonService"
  }
} as const;
