// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file platform/daemon/v1/host.proto (package platform.daemon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ShutdownAlertRequest, ShutdownAlertResponse } from "./host_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * NOTE: this is not currently implemented
 *
 * @generated from service platform.daemon.v1.HostService
 */
export const HostService = {
  typeName: "platform.daemon.v1.HostService",
  methods: {
    /**
     * @generated from rpc platform.daemon.v1.HostService.ShutdownAlert
     */
    shutdownAlert: {
      name: "ShutdownAlert",
      I: ShutdownAlertRequest,
      O: ShutdownAlertResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

