// @generated by protoc-gen-es v1.6.0 with parameter "target=js"
// @generated from file platform/daemon/v1/host.proto (package platform.daemon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.daemon.v1.ShutdownAlertRequest
 */
export const ShutdownAlertRequest = proto3.makeMessageType(
  "platform.daemon.v1.ShutdownAlertRequest",
  [],
);

/**
 * @generated from message platform.daemon.v1.ShutdownAlertResponse
 */
export const ShutdownAlertResponse = proto3.makeMessageType(
  "platform.daemon.v1.ShutdownAlertResponse",
  [],
);

