// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: platform/daemon/v1/stream.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaemonMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*DaemonMessage_Heartbeat
	//	*DaemonMessage_ShutdownAlert
	Message isDaemonMessage_Message `protobuf_oneof:"message"`
}

func (x *DaemonMessage) Reset() {
	*x = DaemonMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonMessage) ProtoMessage() {}

func (x *DaemonMessage) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonMessage.ProtoReflect.Descriptor instead.
func (*DaemonMessage) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (m *DaemonMessage) GetMessage() isDaemonMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *DaemonMessage) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetMessage().(*DaemonMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *DaemonMessage) GetShutdownAlert() *ShutdownAlert {
	if x, ok := x.GetMessage().(*DaemonMessage_ShutdownAlert); ok {
		return x.ShutdownAlert
	}
	return nil
}

type isDaemonMessage_Message interface {
	isDaemonMessage_Message()
}

type DaemonMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof" pg:"heartbeat" bun:"heartbeat" yaml:"heartbeat" csv:"heartbeat" json:"heartbeat"`
}

type DaemonMessage_ShutdownAlert struct {
	ShutdownAlert *ShutdownAlert `protobuf:"bytes,2,opt,name=shutdown_alert,json=shutdownAlert,proto3,oneof" pg:"shutdown_alert" bun:"shutdown_alert" yaml:"shutdown_alert" csv:"shutdown_alert" json:"shutdown_alert"`
}

func (*DaemonMessage_Heartbeat) isDaemonMessage_Message() {}

func (*DaemonMessage_ShutdownAlert) isDaemonMessage_Message() {}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ServerMessage_Heartbeat
	Message isServerMessage_Message `protobuf_oneof:"message"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (m *ServerMessage) GetMessage() isServerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ServerMessage) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetMessage().(*ServerMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof" pg:"heartbeat" bun:"heartbeat" yaml:"heartbeat" csv:"heartbeat" json:"heartbeat"`
}

func (*ServerMessage_Heartbeat) isServerMessage_Message() {}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_stream_proto_rawDescGZIP(), []int{2}
}

type ShutdownAlert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutdownAlert) Reset() {
	*x = ShutdownAlert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_stream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownAlert) ProtoMessage() {}

func (x *ShutdownAlert) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_stream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownAlert.ProtoReflect.Descriptor instead.
func (*ShutdownAlert) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_stream_proto_rawDescGZIP(), []int{3}
}

var File_platform_daemon_v1_stream_proto protoreflect.FileDescriptor

var file_platform_daemon_v1_stream_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0xa5, 0x01, 0x0a, 0x0d, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x4a, 0x0a, 0x0e, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x41, 0x6c, 0x65, 0x72,
	0x74, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x59, 0x0a,
	0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d,
	0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x42, 0x09, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x32, 0x70, 0x0a, 0x13, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x21, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2d, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_daemon_v1_stream_proto_rawDescOnce sync.Once
	file_platform_daemon_v1_stream_proto_rawDescData = file_platform_daemon_v1_stream_proto_rawDesc
)

func file_platform_daemon_v1_stream_proto_rawDescGZIP() []byte {
	file_platform_daemon_v1_stream_proto_rawDescOnce.Do(func() {
		file_platform_daemon_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_daemon_v1_stream_proto_rawDescData)
	})
	return file_platform_daemon_v1_stream_proto_rawDescData
}

var file_platform_daemon_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platform_daemon_v1_stream_proto_goTypes = []interface{}{
	(*DaemonMessage)(nil), // 0: platform.daemon.v1.DaemonMessage
	(*ServerMessage)(nil), // 1: platform.daemon.v1.ServerMessage
	(*Heartbeat)(nil),     // 2: platform.daemon.v1.Heartbeat
	(*ShutdownAlert)(nil), // 3: platform.daemon.v1.ShutdownAlert
}
var file_platform_daemon_v1_stream_proto_depIdxs = []int32{
	2, // 0: platform.daemon.v1.DaemonMessage.heartbeat:type_name -> platform.daemon.v1.Heartbeat
	3, // 1: platform.daemon.v1.DaemonMessage.shutdown_alert:type_name -> platform.daemon.v1.ShutdownAlert
	2, // 2: platform.daemon.v1.ServerMessage.heartbeat:type_name -> platform.daemon.v1.Heartbeat
	0, // 3: platform.daemon.v1.DaemonStreamService.Communicate:input_type -> platform.daemon.v1.DaemonMessage
	1, // 4: platform.daemon.v1.DaemonStreamService.Communicate:output_type -> platform.daemon.v1.ServerMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_platform_daemon_v1_stream_proto_init() }
func file_platform_daemon_v1_stream_proto_init() {
	if File_platform_daemon_v1_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_platform_daemon_v1_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_stream_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_stream_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownAlert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_platform_daemon_v1_stream_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DaemonMessage_Heartbeat)(nil),
		(*DaemonMessage_ShutdownAlert)(nil),
	}
	file_platform_daemon_v1_stream_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ServerMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_daemon_v1_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_daemon_v1_stream_proto_goTypes,
		DependencyIndexes: file_platform_daemon_v1_stream_proto_depIdxs,
		MessageInfos:      file_platform_daemon_v1_stream_proto_msgTypes,
	}.Build()
	File_platform_daemon_v1_stream_proto = out.File
	file_platform_daemon_v1_stream_proto_rawDesc = nil
	file_platform_daemon_v1_stream_proto_goTypes = nil
	file_platform_daemon_v1_stream_proto_depIdxs = nil
}
