// @generated by protoc-gen-es v1.6.0 with parameter "target=js"
// @generated from file platform/daemon/v1/stream.proto (package platform.daemon.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.daemon.v1.DaemonMessage
 */
export const DaemonMessage = proto3.makeMessageType(
  "platform.daemon.v1.DaemonMessage",
  () => [
    { no: 1, name: "heartbeat", kind: "message", T: Heartbeat, oneof: "message" },
    { no: 2, name: "shutdown_alert", kind: "message", T: ShutdownAlert, oneof: "message" },
    { no: 3, name: "os_update_diff", kind: "message", T: OSUpdateDiff, oneof: "message" },
  ],
);

/**
 * @generated from message platform.daemon.v1.ServerMessage
 */
export const ServerMessage = proto3.makeMessageType(
  "platform.daemon.v1.ServerMessage",
  () => [
    { no: 1, name: "heartbeat", kind: "message", T: Heartbeat, oneof: "message" },
    { no: 2, name: "shutdown", kind: "message", T: ShutdownCommand, oneof: "message" },
    { no: 3, name: "restart", kind: "message", T: RestartCommand, oneof: "message" },
    { no: 4, name: "check_os_update_diff", kind: "message", T: CheckOSUpdateDiff, oneof: "message" },
  ],
);

/**
 * @generated from message platform.daemon.v1.Heartbeat
 */
export const Heartbeat = proto3.makeMessageType(
  "platform.daemon.v1.Heartbeat",
  [],
);

/**
 * ShutdownAlert notifies the Server that the host is about to shutdown
 *
 * @generated from message platform.daemon.v1.ShutdownAlert
 */
export const ShutdownAlert = proto3.makeMessageType(
  "platform.daemon.v1.ShutdownAlert",
  [],
);

/**
 * OSUpdateDiff is the result of the `nvd diff` command
 *
 * @generated from message platform.daemon.v1.OSUpdateDiff
 */
export const OSUpdateDiff = proto3.makeMessageType(
  "platform.daemon.v1.OSUpdateDiff",
  () => [
    { no: 1, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * ShutdownCommand tells the daemon to shutdown the host
 *
 * @generated from message platform.daemon.v1.ShutdownCommand
 */
export const ShutdownCommand = proto3.makeMessageType(
  "platform.daemon.v1.ShutdownCommand",
  [],
);

/**
 * RestartCommand tells the daemon to restart the host
 *
 * @generated from message platform.daemon.v1.RestartCommand
 */
export const RestartCommand = proto3.makeMessageType(
  "platform.daemon.v1.RestartCommand",
  [],
);

/**
 * CheckOSUpdateDiff tells the daemon to check for updates to the host and send the update diff back
 *
 * @generated from message platform.daemon.v1.CheckOSUpdateDiff
 */
export const CheckOSUpdateDiff = proto3.makeMessageType(
  "platform.daemon.v1.CheckOSUpdateDiff",
  [],
);

