// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: platform/daemon/v1/system.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time" bun:"start_time" csv:"start_time" pg:"start_time" yaml:"startTime"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time" bun:"end_time" csv:"end_time" pg:"end_time" yaml:"endTime"`
	Compute   *ComputeStats          `protobuf:"bytes,3,opt,name=compute,proto3" json:"compute" bun:"compute" csv:"compute" pg:"compute" yaml:"compute"`
	Memory    *MemoryStats           `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory" bun:"memory" csv:"memory" pg:"memory" yaml:"memory"`
	Drives    []*DriveStats          `protobuf:"bytes,5,rep,name=drives,proto3" json:"drives" bun:"drives" csv:"drives" pg:"drives" yaml:"drives"`
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_system_proto_rawDescGZIP(), []int{0}
}

func (x *SystemStats) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SystemStats) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SystemStats) GetCompute() *ComputeStats {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *SystemStats) GetMemory() *MemoryStats {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemStats) GetDrives() []*DriveStats {
	if x != nil {
		return x.Drives
	}
	return nil
}

type ComputeStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserPercent   float32 `protobuf:"fixed32,1,opt,name=user_percent,json=userPercent,proto3" json:"user_percent" bun:"user_percent" csv:"user_percent" pg:"user_percent" yaml:"userPercent"`
	SystemPercent float32 `protobuf:"fixed32,2,opt,name=system_percent,json=systemPercent,proto3" json:"system_percent" bun:"system_percent" csv:"system_percent" pg:"system_percent" yaml:"systemPercent"`
	IdlePercent   float32 `protobuf:"fixed32,3,opt,name=idle_percent,json=idlePercent,proto3" json:"idle_percent" bun:"idle_percent" csv:"idle_percent" pg:"idle_percent" yaml:"idlePercent"`
}

func (x *ComputeStats) Reset() {
	*x = ComputeStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeStats) ProtoMessage() {}

func (x *ComputeStats) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeStats.ProtoReflect.Descriptor instead.
func (*ComputeStats) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeStats) GetUserPercent() float32 {
	if x != nil {
		return x.UserPercent
	}
	return 0
}

func (x *ComputeStats) GetSystemPercent() float32 {
	if x != nil {
		return x.SystemPercent
	}
	return 0
}

func (x *ComputeStats) GetIdlePercent() float32 {
	if x != nil {
		return x.IdlePercent
	}
	return 0
}

type MemoryStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalBytes     uint32 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes" bun:"total_bytes" csv:"total_bytes" pg:"total_bytes" yaml:"totalBytes"`
	UsedBytes      uint32 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes" bun:"used_bytes" csv:"used_bytes" pg:"used_bytes" yaml:"usedBytes"`
	CachedBytes    uint32 `protobuf:"varint,3,opt,name=cached_bytes,json=cachedBytes,proto3" json:"cached_bytes" bun:"cached_bytes" csv:"cached_bytes" pg:"cached_bytes" yaml:"cachedBytes"`
	FreeBytes      uint32 `protobuf:"varint,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes" bun:"free_bytes" csv:"free_bytes" pg:"free_bytes" yaml:"freeBytes"`
	AvailableBytes uint32 `protobuf:"varint,5,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes" bun:"available_bytes" csv:"available_bytes" pg:"available_bytes" yaml:"availableBytes"`
}

func (x *MemoryStats) Reset() {
	*x = MemoryStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_system_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats) ProtoMessage() {}

func (x *MemoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_system_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats.ProtoReflect.Descriptor instead.
func (*MemoryStats) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryStats) GetTotalBytes() uint32 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryStats) GetUsedBytes() uint32 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *MemoryStats) GetCachedBytes() uint32 {
	if x != nil {
		return x.CachedBytes
	}
	return 0
}

func (x *MemoryStats) GetFreeBytes() uint32 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *MemoryStats) GetAvailableBytes() uint32 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

type DriveStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MountPoint string `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point" bun:"mount_point" csv:"mount_point" pg:"mount_point" yaml:"mountPoint"`
	TotalBytes uint32 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes" bun:"total_bytes" csv:"total_bytes" pg:"total_bytes" yaml:"totalBytes"`
	FreeBytes  uint32 `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes" bun:"free_bytes" csv:"free_bytes" pg:"free_bytes" yaml:"freeBytes"`
}

func (x *DriveStats) Reset() {
	*x = DriveStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_daemon_v1_system_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriveStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveStats) ProtoMessage() {}

func (x *DriveStats) ProtoReflect() protoreflect.Message {
	mi := &file_platform_daemon_v1_system_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveStats.ProtoReflect.Descriptor instead.
func (*DriveStats) Descriptor() ([]byte, []int) {
	return file_platform_daemon_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *DriveStats) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DriveStats) GetTotalBytes() uint32 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DriveStats) GetFreeBytes() uint32 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

var File_platform_daemon_v1_system_proto protoreflect.FileDescriptor

var file_platform_daemon_v1_system_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x02, 0x0a, 0x0b, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x36, 0x0a,
	0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x06, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x73, 0x22, 0x7b, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x64, 0x6c, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x69, 0x64, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x74, 0x22, 0xb8, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x65, 0x65, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x6d, 0x0a,
	0x0a, 0x44, 0x72, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x66, 0x72, 0x65, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x36, 0x5a, 0x34,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2d,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_daemon_v1_system_proto_rawDescOnce sync.Once
	file_platform_daemon_v1_system_proto_rawDescData = file_platform_daemon_v1_system_proto_rawDesc
)

func file_platform_daemon_v1_system_proto_rawDescGZIP() []byte {
	file_platform_daemon_v1_system_proto_rawDescOnce.Do(func() {
		file_platform_daemon_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_daemon_v1_system_proto_rawDescData)
	})
	return file_platform_daemon_v1_system_proto_rawDescData
}

var file_platform_daemon_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platform_daemon_v1_system_proto_goTypes = []any{
	(*SystemStats)(nil),           // 0: platform.daemon.v1.SystemStats
	(*ComputeStats)(nil),          // 1: platform.daemon.v1.ComputeStats
	(*MemoryStats)(nil),           // 2: platform.daemon.v1.MemoryStats
	(*DriveStats)(nil),            // 3: platform.daemon.v1.DriveStats
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_platform_daemon_v1_system_proto_depIdxs = []int32{
	4, // 0: platform.daemon.v1.SystemStats.start_time:type_name -> google.protobuf.Timestamp
	4, // 1: platform.daemon.v1.SystemStats.end_time:type_name -> google.protobuf.Timestamp
	1, // 2: platform.daemon.v1.SystemStats.compute:type_name -> platform.daemon.v1.ComputeStats
	2, // 3: platform.daemon.v1.SystemStats.memory:type_name -> platform.daemon.v1.MemoryStats
	3, // 4: platform.daemon.v1.SystemStats.drives:type_name -> platform.daemon.v1.DriveStats
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_platform_daemon_v1_system_proto_init() }
func file_platform_daemon_v1_system_proto_init() {
	if File_platform_daemon_v1_system_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_platform_daemon_v1_system_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SystemStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_system_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ComputeStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_system_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MemoryStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_daemon_v1_system_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DriveStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_daemon_v1_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_daemon_v1_system_proto_goTypes,
		DependencyIndexes: file_platform_daemon_v1_system_proto_depIdxs,
		MessageInfos:      file_platform_daemon_v1_system_proto_msgTypes,
	}.Build()
	File_platform_daemon_v1_system_proto = out.File
	file_platform_daemon_v1_system_proto_rawDesc = nil
	file_platform_daemon_v1_system_proto_goTypes = nil
	file_platform_daemon_v1_system_proto_depIdxs = nil
}
