// @generated by protoc-gen-es v2.11.0
// @generated from file platform/daemon/v1/system.proto (package platform.daemon.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file platform/daemon/v1/system.proto.
 */
export const file_platform_daemon_v1_system = /*@__PURE__*/
  fileDesc("Ch9wbGF0Zm9ybS9kYWVtb24vdjEvc3lzdGVtLnByb3RvEhJwbGF0Zm9ybS5kYWVtb24udjEi/wEKC1N5c3RlbVN0YXRzEi4KCnN0YXJ0X3RpbWUYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiwKCGVuZF90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIxCgdjb21wdXRlGAMgASgLMiAucGxhdGZvcm0uZGFlbW9uLnYxLkNvbXB1dGVTdGF0cxIvCgZtZW1vcnkYBCABKAsyHy5wbGF0Zm9ybS5kYWVtb24udjEuTWVtb3J5U3RhdHMSLgoGZHJpdmVzGAUgAygLMh4ucGxhdGZvcm0uZGFlbW9uLnYxLkRyaXZlU3RhdHMiUgoMQ29tcHV0ZVN0YXRzEhQKDHVzZXJfcGVyY2VudBgBIAEoAhIWCg5zeXN0ZW1fcGVyY2VudBgCIAEoAhIUCgxpZGxlX3BlcmNlbnQYAyABKAIieQoLTWVtb3J5U3RhdHMSEwoLdG90YWxfYnl0ZXMYASABKAQSEgoKdXNlZF9ieXRlcxgCIAEoBBIUCgxjYWNoZWRfYnl0ZXMYAyABKAQSEgoKZnJlZV9ieXRlcxgEIAEoBBIXCg9hdmFpbGFibGVfYnl0ZXMYBSABKAQiSgoKRHJpdmVTdGF0cxITCgttb3VudF9wb2ludBgBIAEoCRITCgt0b3RhbF9ieXRlcxgCIAEoBBISCgpmcmVlX2J5dGVzGAMgASgEIkEKEENvbXBvbmVudFZlcnNpb24SDAoEbmFtZRgBIAEoCRIOCgZkb21haW4YAiABKAkSDwoHdmVyc2lvbhgDIAEoCSJ0CgNMb2cSDgoGc291cmNlGAEgASgJEhEKCW5hbWVzcGFjZRgCIAEoCRIOCgZkb21haW4YAyABKAkSCwoDbG9nGAQgASgJEi0KCXRpbWVzdGFtcBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAixQEKBERpc2sSDAoEbmFtZRgBIAEoCRITCgtkZXZpY2VfcGF0aBgCIAEoCRINCgVtb2RlbBgDIAEoCRIOCgZzZXJpYWwYBCABKAkSDAoEd3dpZBgFIAEoCRIMCgR1dWlkGAYgASgJEioKBHR5cGUYByABKA4yHC5wbGF0Zm9ybS5kYWVtb24udjEuRGlza1R5cGUSEwoLc3lzdGVtX2Rpc2sYCCABKAgSDAoEc2l6ZRgJIAEoBBIQCghzeW1saW5rcxgKIAMoCSpnCghEaXNrVHlwZRIbChdERVZJQ0VfVFlQRV9VTlNQRUNJRklFRBAAEhMKD0RFVklDRV9UWVBFX1NTRBABEhMKD0RFVklDRV9UWVBFX0hERBACEhQKEERFVklDRV9UWVBFX05WTUUQA0I2WjRnaXRodWIuY29tL2hvbWUtY2xvdWQtaW8vY29yZS9hcGkvcGxhdGZvcm0vZGFlbW9uL3YxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message platform.daemon.v1.SystemStats.
 * Use `create(SystemStatsSchema)` to create a new message.
 */
export const SystemStatsSchema = /*@__PURE__*/
  messageDesc(file_platform_daemon_v1_system, 0);

/**
 * Describes the message platform.daemon.v1.ComputeStats.
 * Use `create(ComputeStatsSchema)` to create a new message.
 */
export const ComputeStatsSchema = /*@__PURE__*/
  messageDesc(file_platform_daemon_v1_system, 1);

/**
 * Describes the message platform.daemon.v1.MemoryStats.
 * Use `create(MemoryStatsSchema)` to create a new message.
 */
export const MemoryStatsSchema = /*@__PURE__*/
  messageDesc(file_platform_daemon_v1_system, 2);

/**
 * Describes the message platform.daemon.v1.DriveStats.
 * Use `create(DriveStatsSchema)` to create a new message.
 */
export const DriveStatsSchema = /*@__PURE__*/
  messageDesc(file_platform_daemon_v1_system, 3);

/**
 * Describes the message platform.daemon.v1.ComponentVersion.
 * Use `create(ComponentVersionSchema)` to create a new message.
 */
export const ComponentVersionSchema = /*@__PURE__*/
  messageDesc(file_platform_daemon_v1_system, 4);

/**
 * Describes the message platform.daemon.v1.Log.
 * Use `create(LogSchema)` to create a new message.
 */
export const LogSchema = /*@__PURE__*/
  messageDesc(file_platform_daemon_v1_system, 5);

/**
 * Describes the message platform.daemon.v1.Disk.
 * Use `create(DiskSchema)` to create a new message.
 */
export const DiskSchema = /*@__PURE__*/
  messageDesc(file_platform_daemon_v1_system, 6);

/**
 * Describes the enum platform.daemon.v1.DiskType.
 */
export const DiskTypeSchema = /*@__PURE__*/
  enumDesc(file_platform_daemon_v1_system, 0);

/**
 * @generated from enum platform.daemon.v1.DiskType
 */
export const DiskType = /*@__PURE__*/
  tsEnum(DiskTypeSchema);

