# permissions for end users to edit installs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: install-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: home-cloud
    app.kubernetes.io/part-of: home-cloud
    app.kubernetes.io/managed-by: kustomize
  name: install-editor-role
rules:
- apiGroups:
  - home-cloud.io
  resources:
  - installs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - home-cloud.io
  resources:
  - installs/status
  verbs:
  - get
