# This rule is not used by the project home-cloud itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to home-cloud.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: home-cloud
    app.kubernetes.io/managed-by: kustomize
  name: wireguard-viewer-role
rules:
- apiGroups:
  - home-cloud.io
  resources:
  - wireguards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - home-cloud.io
  resources:
  - wireguards/status
  verbs:
  - get
