// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=js"
// @generated from file platform/server/v1/internal.proto (package platform.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddMdnsHostRequest, AddMdnsHostResponse, RemoveMdnsHostRequest, RemoveMdnsHostResponse } from "./internal_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.server.v1.InternalService
 */
export const InternalService = {
  typeName: "platform.server.v1.InternalService",
  methods: {
    /**
     * @generated from rpc platform.server.v1.InternalService.AddMdnsHost
     */
    addMdnsHost: {
      name: "AddMdnsHost",
      I: AddMdnsHostRequest,
      O: AddMdnsHostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.server.v1.InternalService.RemoveMdnsHost
     */
    removeMdnsHost: {
      name: "RemoveMdnsHost",
      I: RemoveMdnsHostRequest,
      O: RemoveMdnsHostResponse,
      kind: MethodKind.Unary,
    },
  }
};

