// @generated by protoc-gen-es v1.6.0 with parameter "target=js"
// @generated from file platform/server/v1/internal.proto (package platform.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.server.v1.AddMdnsHostRequest
 */
export const AddMdnsHostRequest = proto3.makeMessageType(
  "platform.server.v1.AddMdnsHostRequest",
  () => [
    { no: 1, name: "hostname", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.server.v1.AddMdnsHostResponse
 */
export const AddMdnsHostResponse = proto3.makeMessageType(
  "platform.server.v1.AddMdnsHostResponse",
  [],
);

/**
 * @generated from message platform.server.v1.RemoveMdnsHostRequest
 */
export const RemoveMdnsHostRequest = proto3.makeMessageType(
  "platform.server.v1.RemoveMdnsHostRequest",
  () => [
    { no: 1, name: "hostname", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.server.v1.RemoveMdnsHostResponse
 */
export const RemoveMdnsHostResponse = proto3.makeMessageType(
  "platform.server.v1.RemoveMdnsHostResponse",
  [],
);

