// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: platform/server/v1/internal.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMdnsHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname" bun:"hostname" csv:"hostname" pg:"hostname" yaml:"hostname"`
}

func (x *AddMdnsHostRequest) Reset() {
	*x = AddMdnsHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_server_v1_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMdnsHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMdnsHostRequest) ProtoMessage() {}

func (x *AddMdnsHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_server_v1_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMdnsHostRequest.ProtoReflect.Descriptor instead.
func (*AddMdnsHostRequest) Descriptor() ([]byte, []int) {
	return file_platform_server_v1_internal_proto_rawDescGZIP(), []int{0}
}

func (x *AddMdnsHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type AddMdnsHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddMdnsHostResponse) Reset() {
	*x = AddMdnsHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_server_v1_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMdnsHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMdnsHostResponse) ProtoMessage() {}

func (x *AddMdnsHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_server_v1_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMdnsHostResponse.ProtoReflect.Descriptor instead.
func (*AddMdnsHostResponse) Descriptor() ([]byte, []int) {
	return file_platform_server_v1_internal_proto_rawDescGZIP(), []int{1}
}

type RemoveMdnsHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname" bun:"hostname" csv:"hostname" pg:"hostname" yaml:"hostname"`
}

func (x *RemoveMdnsHostRequest) Reset() {
	*x = RemoveMdnsHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_server_v1_internal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMdnsHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMdnsHostRequest) ProtoMessage() {}

func (x *RemoveMdnsHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_server_v1_internal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMdnsHostRequest.ProtoReflect.Descriptor instead.
func (*RemoveMdnsHostRequest) Descriptor() ([]byte, []int) {
	return file_platform_server_v1_internal_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveMdnsHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RemoveMdnsHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveMdnsHostResponse) Reset() {
	*x = RemoveMdnsHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_server_v1_internal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMdnsHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMdnsHostResponse) ProtoMessage() {}

func (x *RemoveMdnsHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_server_v1_internal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMdnsHostResponse.ProtoReflect.Descriptor instead.
func (*RemoveMdnsHostResponse) Descriptor() ([]byte, []int) {
	return file_platform_server_v1_internal_proto_rawDescGZIP(), []int{3}
}

var File_platform_server_v1_internal_proto protoreflect.FileDescriptor

var file_platform_server_v1_internal_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x30, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4d, 0x64,
	0x6e, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x41, 0x64, 0x64,
	0x4d, 0x64, 0x6e, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x33, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x64, 0x6e, 0x73, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d,
	0x64, 0x6e, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xde, 0x01, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4d, 0x64, 0x6e, 0x73, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x26, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x64, 0x6e, 0x73, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x64, 0x4d, 0x64, 0x6e, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d,
	0x64, 0x6e, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x29, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x4d, 0x64, 0x6e, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x64,
	0x6e, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68,
	0x6f, 0x6d, 0x65, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_server_v1_internal_proto_rawDescOnce sync.Once
	file_platform_server_v1_internal_proto_rawDescData = file_platform_server_v1_internal_proto_rawDesc
)

func file_platform_server_v1_internal_proto_rawDescGZIP() []byte {
	file_platform_server_v1_internal_proto_rawDescOnce.Do(func() {
		file_platform_server_v1_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_server_v1_internal_proto_rawDescData)
	})
	return file_platform_server_v1_internal_proto_rawDescData
}

var file_platform_server_v1_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platform_server_v1_internal_proto_goTypes = []any{
	(*AddMdnsHostRequest)(nil),     // 0: platform.server.v1.AddMdnsHostRequest
	(*AddMdnsHostResponse)(nil),    // 1: platform.server.v1.AddMdnsHostResponse
	(*RemoveMdnsHostRequest)(nil),  // 2: platform.server.v1.RemoveMdnsHostRequest
	(*RemoveMdnsHostResponse)(nil), // 3: platform.server.v1.RemoveMdnsHostResponse
}
var file_platform_server_v1_internal_proto_depIdxs = []int32{
	0, // 0: platform.server.v1.InternalService.AddMdnsHost:input_type -> platform.server.v1.AddMdnsHostRequest
	2, // 1: platform.server.v1.InternalService.RemoveMdnsHost:input_type -> platform.server.v1.RemoveMdnsHostRequest
	1, // 2: platform.server.v1.InternalService.AddMdnsHost:output_type -> platform.server.v1.AddMdnsHostResponse
	3, // 3: platform.server.v1.InternalService.RemoveMdnsHost:output_type -> platform.server.v1.RemoveMdnsHostResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platform_server_v1_internal_proto_init() }
func file_platform_server_v1_internal_proto_init() {
	if File_platform_server_v1_internal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_platform_server_v1_internal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddMdnsHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_server_v1_internal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddMdnsHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_server_v1_internal_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMdnsHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_server_v1_internal_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMdnsHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_server_v1_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_server_v1_internal_proto_goTypes,
		DependencyIndexes: file_platform_server_v1_internal_proto_depIdxs,
		MessageInfos:      file_platform_server_v1_internal_proto_msgTypes,
	}.Build()
	File_platform_server_v1_internal_proto = out.File
	file_platform_server_v1_internal_proto_rawDesc = nil
	file_platform_server_v1_internal_proto_goTypes = nil
	file_platform_server_v1_internal_proto_depIdxs = nil
}
