// @generated by protoc-gen-es v1.6.0 with parameter "target=js"
// @generated from file platform/server/v1/web.proto (package platform.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.server.v1.ShutdownHostRequest
 */
export const ShutdownHostRequest = proto3.makeMessageType(
  "platform.server.v1.ShutdownHostRequest",
  [],
);

/**
 * @generated from message platform.server.v1.ShutdownHostResponse
 */
export const ShutdownHostResponse = proto3.makeMessageType(
  "platform.server.v1.ShutdownHostResponse",
  [],
);

/**
 * @generated from message platform.server.v1.RestartHostRequest
 */
export const RestartHostRequest = proto3.makeMessageType(
  "platform.server.v1.RestartHostRequest",
  [],
);

/**
 * @generated from message platform.server.v1.RestartHostResponse
 */
export const RestartHostResponse = proto3.makeMessageType(
  "platform.server.v1.RestartHostResponse",
  [],
);

/**
 * @generated from message platform.server.v1.InstallAppRequest
 */
export const InstallAppRequest = proto3.makeMessageType(
  "platform.server.v1.InstallAppRequest",
  () => [
    { no: 1, name: "chart", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "release", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "values", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.server.v1.InstallAppResponse
 */
export const InstallAppResponse = proto3.makeMessageType(
  "platform.server.v1.InstallAppResponse",
  [],
);

/**
 * @generated from message platform.server.v1.DeleteAppRequest
 */
export const DeleteAppRequest = proto3.makeMessageType(
  "platform.server.v1.DeleteAppRequest",
  () => [
    { no: 1, name: "release", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.server.v1.DeleteAppResponse
 */
export const DeleteAppResponse = proto3.makeMessageType(
  "platform.server.v1.DeleteAppResponse",
  [],
);

/**
 * @generated from message platform.server.v1.UpdateAppRequest
 */
export const UpdateAppRequest = proto3.makeMessageType(
  "platform.server.v1.UpdateAppRequest",
  () => [
    { no: 1, name: "chart", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "repo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "release", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "values", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message platform.server.v1.UpdateAppResponse
 */
export const UpdateAppResponse = proto3.makeMessageType(
  "platform.server.v1.UpdateAppResponse",
  [],
);

