name: pkg - CI

on:
  pull_request:
    branches:
      - main
    paths:
      - api/**
      - pkg/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Test `pkg/`
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.26.x']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum

      - name: Test
        working-directory: pkg/
        run: go test ./...
